version: 2.1
orbs:
  docker: circleci/docker@0.2.0
jobs:
  build_and_push:
    docker:
      - image: circleci/openjdk:11
    environment:
      GRADLE_OPTS: -Xmx2048m -Dorg.gradle.daemon=false
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Gradle build
          command: |
            ./gradlew --parallel docker jacocoTestReport sonarqube \
            -Dsonar.projectKey=clouditor_clouditor \
            -Dsonar.organization=clouditor \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - docker/check
      - docker/push:
          image: clouditor/engine
          tag: latest
      - docker/push:
          image: clouditor/ui
          tag: latest
      - docker/push:
          image: clouditor/clouditor
          tag: latest
  build_and_push_eusec:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install API packages
          command: |
            git clone https://github.com/eu-sec/continuous-auditing-api-java-client.git && cd continuous-auditing-api-java-client && ./gradlew install && cd -
      - run:
          name: Gradle build
          command: |
            ./gradlew --parallel docker jacocoTestReport sonarqube \
            -Dsonar.projectKey=clouditor_clouditor \
            -Dsonar.organization=clouditor \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
      - run:
          name: Tag EU-SEC Pilot Build
          command: |
            docker tag clouditor/clouditor clouditor/clouditor:eu-sec
      - docker/check
      - docker/push:
          image: clouditor/clouditor
          tag: eu-sec
  build:
    docker:
      - image: circleci/openjdk:11
    environment:
      GRADLE_OPTS: -Xmx2048m -Dorg.gradle.daemon=false
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Gradle build
          command: |
            ./gradlew --parallel docker jacocoTestReport sonarqube \
            -Dsonar.projectKey=clouditor_clouditor \
            -Dsonar.organization=clouditor \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
workflows:
  build:
    jobs:
      - build_and_push:
          context: org-global
          filters:
            branches:
              only:
              - master
      - build_and_push_eusec:
          context: org-global
          filters:
            branches:
              only:
                - eu-sec
      - build:
          context: org-global
          filters:
            branches:
              ignore:
              - master
              - eu-sec
